### ISSUE TITLE
Error: Cannot find module './styles.scss'

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/custom-field-guide#2]
Cool extra custom field!

Everyting works perfect when I run Payload in dev mode but when I build en serve payload i get this error:
```
[15:53:33] INFO (payload): Starting Payload...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './styles.scss'
Require stack:
- C:\Users\*\Documents\*\backend\dist\blocks\custom-fields\color-picker\component.js
- C:\Users\*\Documents\*\backend\dist\blocks\custom-fields\color-picker\index.js
- C:\Users\*\Documents\*\backend\dist\blocks\sections\Divider.js
- C:\Users\*\Documents\*\backend\dist\blocks\section-list.js
- C:\Users\*\Documents\*\backend\dist\collections\Page.js
- C:\Users\*\Documents\*\backend\dist\payload.config.js
- C:\Users\*\Documents\*\backend\node_modules\payload\dist\config\load.js
- C:\Users\*\Documents\*\backend\node_modules\payload\dist\init.js
- C:\Users\*\Documents\*\backend\node_modules\payload\dist\index.js
- C:\Users\*\Documents\*\backend\dist\server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\*\Documents\*\backend\dist\blocks\custom-fields\color-picker\/component.js:73:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Module._compile (C:\Users\*\Documents\*\backend\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (C:\Users\*\Documents\*\backend\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\*\\Documents\\*\\backend\\dist\\blocks\\custom-fields\\color-picker\\component.js',
    'C:\\Users\\*\\Documents\\*\\backend\\dist\\blocks\\custom-fields\\color-picker\\index.js',
    'C:\\Users\\*\\Documents\\*\\backend\\dist\\blocks\\sections\\Divider.js',
    'C:\\Users\\*\\Documents\\*\\backend\\dist\\blocks\\section-list.js',
    'C:\\Users\\*\\Documents\\*\\backend\\dist\\collections\\Page.js',
    'C:\\Users\\*\\Documents\\*\\backend\\dist\\payload.config.js',
    'C:\\Users\\*\\Documents\\*\\backend\\node_modules\\payload\\dist\\config\\load.js',
    'C:\\Users\\*\\Documents\\*\\backend\\node_modules\\payload\\dist\\init.js',
    'C:\\Users\\*\\Documents\\*\\backend\\node_modules\\payload\\dist\\index.js',
    'C:\\Users\\*\\Documents\\*\\backend\\dist\\server.js'
  ]
}
```

I got payload 1.0.11

**Comment by matthijs166** [comment]
It also doesn't work when I clone the whole repo
I see that there is no package lock so maybe a dependency was updated
